MUSIC_DIFF_ESY = 1
MUSIC_DIFF_STD = 2
MUSIC_DIFF_HRD = 3
MUSIC_DIFF_MAS = 4
MUSIC_DIFF_UNL = 5

MUSIC_DIFFS = {
    MUSIC_DIFF_ESY => 'ESY',
    MUSIC_DIFF_STD => 'STD',
    MUSIC_DIFF_HRD => 'HRD',
    MUSIC_DIFF_MAS => 'MAS',
    MUSIC_DIFF_UNL => 'UNL',
}
