SITE_MODE = [:cxb, :rev][0]

MUSIC_DIFF_ESY = 1
MUSIC_DIFF_STD = 2
MUSIC_DIFF_HRD = 3
MUSIC_DIFF_MAS = 4
MUSIC_DIFF_UNL = 5

MUSIC_DIFFS_ALL = {
  MUSIC_DIFF_ESY => 'ESY',
  MUSIC_DIFF_STD => 'STD',
  MUSIC_DIFF_HRD => 'HRD',
  MUSIC_DIFF_MAS => 'MAS',
  MUSIC_DIFF_UNL => 'UNL',
}

MUSIC_DIFFS = {
  cxb: MUSIC_DIFFS_ALL.dup.delete_if do |k, v| [MUSIC_DIFF_ESY, MUSIC_DIFF_UNL].include? k end,
  rev: MUSIC_DIFFS_ALL,
}

SKILL_STAT_NO_PLAY = 0
SKILL_STAT_FAILED  = 1
SKILL_STAT_CLEARED = 2

SKILL_GAUGE_NORMAL = 0
SKILL_GAUGE_SURVIVAL = 1
SKILL_GAUGE_ULTIMATE = 2

SKILL_GAUGES_ALL = {
  SKILL_GAUGE_NORMAL   => 'NORMAL',
  SKILL_GAUGE_SURVIVAL => 'SURVIVAL',
  SKILL_GAUGE_ULTIMATE => 'ULTIMATE',
}

SKILL_GAUGES = {
  cxb: SKILL_GAUGES_ALL.dup.delete_if do |k, v| [SKILL_GAUGE_SURVIVAL].include? k end,
  rev: SKILL_GAUGES_ALL,
}
SKILL_GAUGE_BONUS_RATES = {
  SKILL_GAUGE_NORMAL   => 1.0,
  SKILL_GAUGE_SURVIVAL => 1.1,
  SKILL_GAUGE_ULTIMATE => 1.2,
}

SKILL_COMBO_NO = 0
SKILL_COMBO_FC = 1
SKILL_COMBO_EXC = 2

SKILL_COMBOS_ALL = {
  SKILL_COMBO_NO  => '',
  SKILL_COMBO_FC  => 'FC',
  SKILL_COMBO_EXC => 'EXC',
}
